### ISSUE TITLE
ava-smartboard用官网示例出现了报错

### ISSUE THREAD

**Issue by gabrielpondc** [antvis/AVA#776]
```js
import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { getDataInsights } from '@antv/lite-insight';
import { SmartBoard, SmartBoardDashboard, insights2Board } from '@antv/smart-board';

const App = () => {
  const [insights, setInsights] = useState({});
  const [data, setData] = useState([]);
  const [smartBoard, setSmartBoard] = useState();
  const [isLoading, setIsLoading] = useState(true);

  const fetchDataset = async () => {
    fetch('https://cdn.jsdelivr.net/npm/vega-datasets@2.2.0/data/gapminder.json')
      .then((res) => res.json())
      .then((data) => {
        if (data) {
          setData(data);
          const insightResult = getDataInsights(data, {
            limit: 10,
            measures: [
              { field: 'life_expect', method: 'MEAN' },
              { field: 'pop', method: 'SUM' },
              { field: 'fertility', method: 'MEAN' },
            ],
            // 洞察结果中会增加对应的可视化展示方案（基于g2plot）
            visualization: true,
          });
          setInsights(insightResult);
          setIsLoading(false);
        }
      });
  };

  useEffect(() => {
    fetchDataset();
  }, []);

  useEffect(() => {
    if (insights?.insights) {
      const updateSmartBoard = new SmartBoard(insights2Board(insights.insights));
      setSmartBoard(updateSmartBoard);
    }
  }, [insights]);

  return (
    <>
      <p>Represent insight with smart-board.</p>

          <div >
            <SmartBoardDashboard
              chartList={insights2Board(insights.insights)}
              interactionMode={'defaultMode'}
              hasInsight={true}
              chartGraph={smartBoard?.chartGraph}
              chartOrder={smartBoard?.chartOrder('byInsightScore')}
              chartCluster={smartBoard?.chartCluster()}
            />
          </div>

    </>
  );
};

ReactDOM.render(<App />, document.getElementById('root'));
```
报错内容
```js
defaultBoard.js:10 
 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at SmartBoardDashboard (defaultBoard.js:10:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
```

```js
The above error occurred in the <SmartBoardDashboard> component:

    at SmartBoardDashboard (http://10.1.51.23:9810/static/js/bundle.js:262753:25)
    at div
    at App (http://10.1.51.23:9810/static/js/bundle.js:32:82)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```

```js
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at SmartBoardDashboard (defaultBoard.js:10:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at performSyncWorkOnRoot (react-dom.development.js:26085:1)
    at flushSyncCallbacks (react-dom.development.js:12042:1)
```

**Comment by gabrielpondc** [comment]
检查了insights2Board(insights.insights)数据样式一切正常，就是会报`Cannot read properties of undefined (reading 'length')`的相关错误

**Comment by chenluli** [comment]
可以提供可复现的在线 CodeSandbox 链接么，原官网示例未复现。
另外，在 ava v3 版本中 https://ava.antv.antgroup.com/guide/migrate/tov3fromv2，SmartBoard 已暂时下线，不再推荐使用，相关问题的修复可能不及时 🙇。目前推荐使用 v3 版本中的 getInsights api 得到洞察数据后，结合 <InsightCard/> 展示，参考：https://ava.antv.antgroup.com/examples/insight/custom/#insight-type 样例

<img width="880" alt="Screenshot 2024-03-14 at 11 34 00 AM" src="https://github.com/antvis/AVA/assets/16997933/d3d9dfb2-5749-4c4d-951a-f03bdd050446">

**Comment by gabrielpondc** [comment]
了解，主要还是想尝试自动洞察+Smaetboard的相关功能，https://codesandbox.io/p/sandbox/kind-dust-0s8139?

**Comment by gabrielpondc** [comment]
了解，还是想使用Smartboard+自动洞察这个功能，好像是数据样式的问题，目前已经解决
